version: '3.8'
services:
  api:
    container_name: cloud-inventory-api
    build:
      context: ./backend
      target: api
      dockerfile: Dockerfile
    env_file:
      - backend/env/api
    networks:
      - backend
    depends_on:
      - maildev
      - postgres
      - redis
  cli:
    container_name: cloud-inventory-cli
    build:
      context: ./backend
      target: cli
      dockerfile: Dockerfile
    volumes:
      - ./backend/cmd/cli/commands/migrations:/migrations
    networks:
      - backend
    env_file:
      - backend/env/postgres
    depends_on:
      - postgres
  gateway:
    container_name: cloud-inventory-gateway
    build:
      context: ./backend
      target: gateway
      dockerfile: Dockerfile
    env_file:
      - backend/env/gateway
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - api
  ui:
    container_name: cloud-inventory-ui
    build:
      context: ./frontend/cloud-inventory-spa
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      backend:
        aliases:
          - cloud-inventory-ui.local
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
    networks:
      - backend
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge